"""Initial setup

Revision ID: 15c5fb2a1b7b
Revises: 
Create Date: 2025-09-28 20:50:42.605506

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c5fb2a1b7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_account_name'), 'account', ['account_name'], unique=False)
    op.create_index(op.f('ix_account_email_address'), 'account', ['email_address'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_crawl_date', sa.DateTime(), nullable=True),
    sa.Column('age_window', sa.Integer(), nullable=False),
    sa.Column('crawl_page_content', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url', 'created_by', name='uq_feed_url_created_by')
    )
    op.create_index(op.f('ix_feeds_created_by'), 'feeds', ['created_by'], unique=False)
    op.create_table('entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_index(op.f('ix_feeds_created_by'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_account_email_address'), table_name='account')
    op.drop_index(op.f('ix_account_account_name'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
