"""Add latest entry date to feed

Revision ID: 4d8f7ae8c980
Revises: d38cf7e37f36
Create Date: 2026-06-13 20:36:20.938301

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8f7ae8c980'
down_revision: Union[str, Sequence[str], None] = 'd38cf7e37f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('latest_entry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'latest_entry_date')
    # ### end Alembic commands ###
