"""Add unique constraint to email and account name

Revision ID: 4f40d6968a24
Revises: 2359972e2837
Create Date: 2025-09-30 21:25:45.152563

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f40d6968a24'
down_revision: Union[str, Sequence[str], None] = '2359972e2837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_account_name'), table_name='account')
    op.create_index(op.f('ix_account_account_name'), 'account', ['account_name'], unique=True)
    op.drop_index(op.f('ix_account_email_address'), table_name='account')
    op.create_index(op.f('ix_account_email_address'), 'account', ['email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_email_address'), table_name='account')
    op.create_index(op.f('ix_account_email_address'), 'account', ['email_address'], unique=False)
    op.drop_index(op.f('ix_account_account_name'), table_name='account')
    op.create_index(op.f('ix_account_account_name'), 'account', ['account_name'], unique=False)
    # ### end Alembic commands ###
