"""Add filter fields

Revision ID: d38cf7e37f36
Revises: 4f40d6968a24
Create Date: 2026-03-04 07:20:42.505779

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38cf7e37f36'
down_revision: Union[str, Sequence[str], None] = '4f40d6968a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('link_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('feeds', sa.Column('page_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'page_filter')
    op.drop_column('feeds', 'link_filter')
    # ### end Alembic commands ###
